# Generated by Django 2.2.27 on 2023-02-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('invoice_number', models.BigIntegerField(verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Заказ c GetCourse',
                'verbose_name_plural': 'Заказы c GetCourse',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_from_gc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaking_clubs.OrderGC', verbose_name='Заказ с GetCourse'),
        ),
    ]
