# Generated by Django 2.2.27 on 2023-03-05 22:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0002_auto_20230212_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.UUIDField(verbose_name='№ задания')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Ответ')),
                ('users', models.ManyToManyField(blank=True, to='speaking_clubs.Student', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ ученика',
                'verbose_name_plural': 'Ответы учеников',
            },
        ),
    ]
