# Generated by Django 2.2.27 on 2023-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0004_auto_20230306_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Среда - Пятница', 'Понедельник - Среда - Пятница'), ('Понедельник - Среда - Суббота', 'Понедельник - Среда - Суббота')], max_length=255, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Среда - Пятница', 'Понедельник - Среда - Пятница'), ('Понедельник - Среда - Суббота', 'Понедельник - Среда - Суббота')], max_length=255, verbose_name='Дни недели'),
        ),
    ]
