# Generated by Django 2.2.27 on 2023-05-02 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0005_auto_20230309_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'nav-Grammar': -1, 'nav-Listening': -1, 'nav-Reading': -1, 'nav-Vocabulary': -1, 'nav-Writing': -1}, null=True, verbose_name='Результаты тестов'),
        ),
    ]
