# Generated by Django 2.2.27 on 2023-05-02 17:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0006_auto_20230502_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Результаты тестов'),
        ),
    ]
