# Generated by Django 2.2.27 on 2023-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0008_auto_20230502_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekdays',
            field=models.CharField(blank=True, choices=[('Понедельник - Среда - Пятница', 'Понедельник - Среда - Пятница'), ('Понедельник - Среда - Суббота', 'Понедельник - Среда - Суббота')], max_length=255, null=True, verbose_name='Дни недели'),
        ),
    ]
