# Generated by Django 2.2.27 on 2023-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0009_auto_20230502_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Понедельник - Суббота', 'Понедельник - Суббота')], max_length=255, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekdays',
            field=models.CharField(blank=True, choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Понедельник - Суббота', 'Понедельник - Суббота')], max_length=255, null=True, verbose_name='Дни недели'),
        ),
    ]
