# Generated by Django 2.2.27 on 2023-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0011_auto_20230514_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='С олатой'),
        ),
    ]
