# Generated by Django 2.2.27 on 2023-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0012_student_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='С оплатой'),
        ),
    ]
