# Generated by Django 2.2.27 on 2023-05-28 23:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def insert_data(apps, schema_editor):
    MyModel = apps.get_model('speaking_clubs', 'Stream')
    MyModel.objects.create(
        name='Поток 14',
        gc_name='Lectures XIV',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0014_auto_20230514_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=255, verbose_name='Название')),
                    ('gc_name', models.CharField(max_length=255, verbose_name='Название в заказе')),],
            options={'verbose_name': 'Поток', 'verbose_name_plural': 'Потоки', },),
        migrations.AlterField(
            model_name='student', name='test', field=django.contrib.postgres.fields.jsonb.JSONField(
                default={'nav-Grammar': -1, 'nav-Listening': -1, 'nav-Reading': -1, 'nav-Vocabulary': -1, 'nav-Writing': -1},
                verbose_name='Результаты тестов'),),
        migrations.AddField(
            model_name='chat', name='stream', field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_clubs.Stream', verbose_name='Поток'),),
        migrations.AddField(
            model_name='ordergc', name='stream', field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='speaking_clubs.Stream', verbose_name='Поток'),
            preserve_default=False,),
        migrations.AddField(
            model_name='student', name='stream', field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_clubs.Stream', verbose_name='Поток'),),
        migrations.RunPython(insert_data),]
