# Generated by Django 2.2.27 on 2023-05-29 00:31


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count


def insert_data(apps, schema_editor):
    Stream = apps.get_model('speaking_clubs', 'Stream')
    Student = apps.get_model('speaking_clubs', 'Student')
    Chat = apps.get_model('speaking_clubs', 'Chat')
    Order = apps.get_model('speaking_clubs', 'Order')

    stream = Stream.objects.filter(name='Поток 14').first()

    chats = Chat.objects.annotate(
        students_count=Count('students')
    ).filter(
        students_count__gt=0,
    ).all()

    for chat in chats:
        chat.stream = stream
        chat.save()

    students = Student.objects.all()

    for student in students:

        order = Order.objects.filter(
            user=student.user,
        ).first()

        if order and order.order_from_gc:
            student.stream = order.order_from_gc.stream
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0015_auto_20230528_2331'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
