# Generated by Django 2.2.27 on 2023-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0017_auto_20230802_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_done_by_manager',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
